### ISSUE TITLE
No download available

### ISSUE THREAD

**Issue by AGSPhoenix** [DCS-gRPC/Telemachus#1]
The README says to download Telemachus "from URL", but doesn't actually provide a link, and there are no GitHub releases. Is a prebuilt binary intended to be available?

**Comment by rurounijones** [comment]
There is no official release for Telemachus yet. An initial release will occur sometime in November.

**Comment by rurounijones** [comment]
Welp... It is now January and no official release. There is a single issue I am having trouble fixing. Apologies for the delay

**Comment by rurounijones** [comment]
https://github.com/DCS-gRPC/Telemachus/releases/tag/0.1.0
